### PR TITLE
realpath Warning fixed

### PR DESCRIPTION
**Pull request by ajphukan**
resolve the realpath error

### CODE REVIEW

**Comment by andy5995** [comment]
The warning is gone, but if you run rmw with your patch you'll see that realpath is returning NULL even though it's finding the realpath. That's not your fault though. I have an idea on how to fix it after reading http://stackoverflow.com/questions/33550771/my-realpath-return-null-for-files?rq=1

I'm going to do a little work on it. Stay tuned - we both may learn something. :)

**Comment by ajphukan** [comment]
okk ...

**Comment by andy5995** [comment]
Oh, but get some sleep if you need to! :) This may take a while...

**Comment by ajphukan** [comment]
sure . okk gd night ...:)

**Comment by andy5995** [comment]
@ajphukan I think I've worked it all out.

https://github.com/andy5995/rmw/commit/93ea19dbc79880537025b98721c6139900802363

I was able to get realpath() to not return a NULL when I concatenated the PWD to the src string.

Then the problem was that symbolics links turned into the actual paths, not the path to the symlink.

So I decided to drop the use of realpath altogether.

Let me know if you have questions. It would be good if you examine the resolve_path() function and understood it.

This takes care of #55 though.

**Pull request closed without merging**
