### PR TITLE
Dev2 change

### PR DESCRIPTION
**Pull request by ajphukan**
Changes ..

### CODE REVIEW

**Comment by andy5995** [comment]
These changes are compared against main.c from before you made your first edits, so can't be merged with the PR that I already merged from you.

You need to switch back to the develop branch, and sync your repo.

See https://github.com/andy5995/rmw/wiki/Contributing -> Syncing

Let me know if you have any questions. If you get stuck, probably better not to guess, and just wait for me to reply. Right now, I'm headed out for the night. Thanks for your contributions @ajphukan.

**Comment by ajphukan** [comment]
Okk @andy5995   .  
Is there any other way i can communicate with you ..
Whenever i use IRC i face problem .

**Comment by andy5995** [comment]
Tomorrow we will try to solve the IRC problem. Try installing HexChat IRC client and we'll try tomorrow.

**Comment by ajphukan** [comment]
okk ..

**Pull request closed without merging**
