### PR TITLE
Display file size during --select

### PR DESCRIPTION
**Pull request by suve**
This changeset makes the list of files during `--select` display the file sizes along the file names. This should resolve issue #68.

### CODE REVIEW

**Comment by andy5995** [comment]
This is cool!

Patch worked for me. Nice! Would you mind adding a declaration  for the function prototype of `human_readable_size()` to restore_rmw.h ?

**Comment by suve** [comment]
I've declared that function as `static`. If you want it to be exported, I wonder if it wouldn't be better to put it in `strings_rmw`, or maybe even create an `utils_rmw` file.

**Comment by andy5995** [comment]
In this case, why don't you do what you think is best. And if you think it's fine as is, I'll go ahead and merge it.

**Comment by suve** [comment]
Eh. I'd leave it as-is. If there's a need to use this function somewhere else, adding an export to the `.h.` file or moving it somewhere else takes a couple seconds.

**Pull request merged**
